# Generated by Django 4.0.3 on 2022-04-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetPhpExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='MeetPhp Images')),
                ('message', models.TextField(max_length=1000)),
            ],
            options={
                'db_table': 'MeetPhpExpert',
            },
        ),
    ]
