# Generated by Django 4.0.3 on 2022-05-05 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WebApp', '0003_androidquestion_cplusplusquestion_csharpquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JavascriptCreateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='JavascriptProfile Images/')),
            ],
            options={
                'db_table': 'JavascriptCreateProfile',
            },
        ),
        migrations.CreateModel(
            name='JavascriptVideoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('video', models.FileField(upload_to='javascriptVideo/')),
                ('create_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeetJavascriptExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='MeetJavascript Images/')),
                ('message', models.TextField(max_length=1000)),
            ],
            options={
                'db_table': 'MeetJavascriptExpert',
            },
        ),
        migrations.RenameModel(
            old_name='JavaQuestion',
            new_name='PhpQuestion1',
        ),
        migrations.RenameModel(
            old_name='FlutterQuestion',
            new_name='PhpQuestion2',
        ),
        migrations.RenameModel(
            old_name='PhpQuestion',
            new_name='PhpQuestion3',
        ),
        migrations.RenameModel(
            old_name='PythonQuestion',
            new_name='PhpQuestion4',
        ),
        migrations.DeleteModel(
            name='AndroidQuestion',
        ),
        migrations.DeleteModel(
            name='CplusplusQuestion',
        ),
        migrations.DeleteModel(
            name='CsharpQuestion',
        ),
        migrations.DeleteModel(
            name='ReactnativeQuestion',
        ),
    ]
